<?php
    // Twitter
    $this->inlineScript()->appendFile('//platform.twitter.com/widgets.js');

    // Facebook
    echo '<div id="fb-root"></div>';
    $this->inlineScript()->captureStart();
    echo '(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.3";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, \'script\', \'facebook-jssdk\'));';
    $this->inlineScript()->captureEnd();

    // Pinterest
    $this->inlineScript()->appendFile('//assets.pinterest.com/js/pinit.js');
?>
<div class="fb-like" data-href="https://www.facebook.com/pages/Moneysavingnews/351084198414165" data-layout="button" data-action="like" data-show-faces="false" data-share="false"></div>
<a class="twitter-follow-button" href="https://twitter.com/MoneySavingNews" data-show-count="false">Follow @MoneySavingNews</a>
<a data-pin-do="buttonFollow" href="http://www.pinterest.com/moneysavingnews/">MoneySavingNews</a>