<main class="competition">
    <div class="row">
        <div class="large-12 show-for-large-up column text-right social-widgets">
            <?php echo $this->partial('money-saving-news/partial/social-includes'); ?>
        </div>
    </div>
    <div class="row">
        <div class="small-12 column">
            <section class="competition-index">
                <h1>
                    Competitions
                </h1>
                <p>
                    Coming soon.
                </p>
                <p>
                    <a href="<?php echo $this->url('root'); ?>">&laquo; Back to homepage</a>
                </p>
            </section>
        </div>
    </div>
</main>