<?php

return [
    'controllers' => [
        'invokables' => [
            'Ed\Msn\Controller\Index' => 'Ed\Msn\Controller\IndexController',
            'Ed\Msn\Controller\Competition' => 'Ed\Msn\Controller\CompetitionController',
        ],
        'factories' => [
            'Ed\Msn\Controller\Article' => 'Ed\Msn\Controller\ArticleControllerFactory',
        ],
    ],
    'service_manager' => [
        'invokables' => [
        ],
        'factories' => [
            'Ed\Msn\Service\Session' => 'Ed\Msn\Service\SessionFactory',
            'Ed\Msn\ActionFilter\Metadata' => 'Ed\Msn\ActionFilter\MetadataFactory',
        ],
        'aliases' => [
            'session' => 'Ed\Msn\Service\Session',
        ],
    ],
    'action_filters' => [
        'Ed\Msn\ActionFilter\Metadata' => [
            'event' => 'dispatch',
            'priority' => 50,
        ],
    ],
    'router' => [
        'routes' => [
            'root' => include 'routes/root.config.php',
        ],
    ],
    'view_manager' => [
        'layout' => 'layout/layout',
        'display_not_found_reason' => true,
        'display_exceptions' => true,
        'doctype' => 'HTML5',
        'not_found_template' => 'error/404',
        'exception_template' => 'error/index',
        'template_map' => [
            'layout/layout' => __DIR__ . '/../view/layout/layout.phtml',
            'error/404' => __DIR__ . '/../view/error/404.phtml',
            'error/index' => __DIR__ . '/../view/error/index.phtml',
        ],
        'template_path_stack' => [
            __DIR__ . '/../view',
        ],
    ],
    'view_helpers' => [
        'invokables' => [
            'Ed\Msn\View\Helper\ReferralLink' => 'Ed\Msn\View\Helper\ReferralLink',
        ],
        'factories' => [
            'Ed\Msn\View\Helper\EdDevelopment' => 'Ed\Msn\View\Helper\EdDevelopmentFactory',
            'Ed\Msn\View\Helper\Pixels' => 'Ed\Msn\View\Helper\PixelsFactory',
            'Ed\Msn\View\Helper\Categories' => 'Ed\Msn\View\Helper\CategoriesFactory',
            'Ed\Msn\View\Helper\Articles' => 'Ed\Msn\View\Helper\ArticlesFactory',
        ],
        'aliases' => [
            'edDevelopment' => 'Ed\Msn\View\Helper\EdDevelopment',
            'pixels' => 'Ed\Msn\View\Helper\Pixels',
            'categories' => 'Ed\Msn\View\Helper\Categories',
            'articles' => 'Ed\Msn\View\Helper\Articles',
            'referralLink' => 'Ed\Msn\View\Helper\ReferralLink',
        ],
    ],
    'msn' => [
        'categories' => [
            'career' => 'Career',
            'finance' => 'Finance',
            'health-and-beauty' => 'Health &amp; Beauty',
            'lifestyle' => 'Lifestyle',
            'relationship' => 'Relationship',
            'technology' => 'Technology',
            'travel' => 'Travel',
        ],
        'articles' => [
            /*
                'url' => [
                    'linkText' => 'Link text',
                    'date' => 'YYYY-MM-DD',
                    'trackingCode' => 'ACB123',
                    'category' => 'career',
                    'thumbnail' => true,
                    'isAdvertorial' => false,
                ],
            */
            'she-invited-him-back-to-her-house-but-he-wasnt-expecting-this' => [
                'linkText' => 'She invited him back to her house – but he wasn&rsquo;t expecting this!',
                'date' => '2015-06-01',
                'trackingCode' => '',
                'category' => 'relationship',
                'thumbnail' => false,
            ],
            'change-your-life-in-a-week-with-coconut-oil' => [
                'linkText' => 'Change your life in a week - with coconut oil!',
                'date' => '2015-06-03',
                'trackingCode' => '',
                'category' => 'health-and-beauty',
                'thumbnail' => true,
            ],
            '5-things-that-were-invented-by-accident' => [
                'linkText' => '5 things that were invented by accident!',
                'date' => '2015-06-04',
                'trackingCode' => '',
                'category' => 'technology',
                'thumbnail' => true,
            ],
            '7-of-the-craziest-insurance-policies' => [
                'linkText' => '7 of the craziest insurance policies',
                'date' => '2015-06-04',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => true,
            ],
            '9-genius-life-hacks-you-didnt-know-you-needed' => [
                'linkText' => '9 genius life hacks you didn&rsquo;t know you needed',
                'date' => '2015-06-03',
                'trackingCode' => '',
                'category' => 'lifestyle',
                'thumbnail' => true,
            ],
            'you-wont-believe-these-trees-actually-exist' => [
                'linkText' => 'You won&rsquo;t believe these trees actually exist!',
                'date' => '2015-06-03',
                'trackingCode' => '',
                'category' => 'travel',
                'thumbnail' => true,
            ],
            '15-very-rare-photos-from-the-past' => [
                'linkText' => '15 Very Rare Photos From The Past That Will Blow Your Mind',
                'date' => '2015-06-03',
                'trackingCode' => '',
                'category' => 'technology',
                'thumbnail' => true,
            ],
            'you-wont-believe-whats-inside-these-cakes' => [
                'linkText' => 'You won&rsquo;t believe what&rsquo;s inside these cakes!',
                'date' => '2015-06-05',
                'trackingCode' => '',
                'category' => 'lifestyle',
                'thumbnail' => true,
            ],
            '1-simple-trick-to-protect-your-family-for-10-per-month' => [
                'linkText' => '1 Simple Trick to Protect Your Family for &pound;10/month',
                'date' => '2015-06-08',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => true,
            ],
            'you-wont-believe-what-tigers-can-do' => [
                'linkText' => 'You won&rsquo;t believe what tigers can do!',
                'date' => '2015-06-19',
                'trackingCode' => '',
                'category' => 'travel',
                'thumbnail' => true,
            ],
            '5-amazing-hybrid-animals' => [
                'linkText' => '5 amazing hybrid animals',
                'date' => '2015-06-19',
                'trackingCode' => '',
                'category' => 'travel',
                'thumbnail' => true,
            ],
            'i-bet-you-never-knew-this-about-ginger' => [
                'linkText' => 'I bet you never knew this about Ginger!',
                'date' => '2015-06-22',
                'trackingCode' => '',
                'category' => 'health-and-beauty',
                'thumbnail' => true,
            ],
            'crazy-pictures-that-will-blow-you-away-number-5-had-me-floored' => [
                'linkText' => 'Crazy pictures that will blow you away! Number 5 had me floored!',
                'date' => '2015-06-22',
                'trackingCode' => '',
                'category' => 'lifestyle',
                'thumbnail' => true,
            ],
            'top-5-mistakes-when-buying-life-insurance' => [
                'linkText' => 'Top 5 Mistakes when Buying Life Insurance',
                'date' => '2015-10-05',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
        ],
        'landingPages' => [
            /*
                'url' => [
                    'linkText' => 'Link text',
                    'date' => 'YYYY-MM-DD',
                    'trackingCode' => 'ACB123',
                    'category' => 'career',
                    'thumbnail' => true,
                    'isAdvertorial' => true,
                ],
            */
            '1-simple-trick-to-protect-your-family-for-ten-pounds' => [
                'linkText' => '1 Simple Trick to Protect Your Family for Ten Pounds',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            '1-simple-trick-to-protect-your-family-for-ten-pounds-2' => [
                'linkText' => '1 Simple Trick to Protect Your Family for Ten Pounds',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            '1-simple-trick-to-protect-your-familys-future' => [
                'linkText' => '1 Simple Trick to Protect Your Family&rsquo;s Future',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            '1-simple-trick-to-protect-your-familys-future-2' => [
                'linkText' => '1 Simple Trick to Protect Your Family&rsquo;s Future',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            'life-insurance-companies-hate-this-trick' => [
                'linkText' => 'Life Insurance companies hate this trick - Smart families get &pound;10 life cover',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
                'isAdvertorial' => true,
            ],
            'life-insurance-companies-profits-take-a-big-hit' => [
                'linkText' => 'Life Insurance companies profits take a big hit: Smart families uncover secrets to &pound;10 life cover',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            'one-simple-trick-to-protect-your-familys-future' => [
                'linkText' => 'One Simple Trick to Protect Your Family&rsquo;s Future',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            '1-simple-trick-to-10-per-month-life-insurance' => [
                'linkText' => '1 Simple Trick to &pound;10 per month Life Insurance',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
                'isAdvertorial' => true,
            ],
            'new-policy-in-the-uk-simple-trick-to-save-your-family-thousands' => [
                'linkText' => 'New Policy in the UK: Simple Trick to Save Your Family Thousands',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            'new-policy-in-the-uk-if-you-dont-have-life-insurance-you-better-read-this' => [
                'linkText' => 'New Policy in UK – If you Don&rsquo;t Have Life Insurance You Better Read This&hellip;',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            'life-insurance-companies-hate-this-trick-2' => [
                'linkText' => 'Life Insurance companies hate this trick - Smart families get &pound;10 life cover',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            'life-insurance-companies-hate-this-trick-3' => [
                'linkText' => 'Life Insurance companies hate this trick - Smart families get &pound;10 life cover',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
                'isAdvertorial' => true,
            ],
            'life-insurance-companies-profits-take-a-big-hit-2' => [
                'linkText' => 'Life Insurance companies profits take a big hit: Smart families uncover secrets to &pound;10 life cover',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            'life-insurance-companies-profits-take-a-big-hit-3' => [
                'linkText' => 'Life Insurance companies profits take a big hit: Smart families uncover secrets to &pound;10 life cover',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            'one-simple-trick-to-protect-your-familys-future-2' => [
                'linkText' => 'One Simple Trick to Protect Your Family&rsquo;s Future',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            'one-simple-trick-to-protect-your-familys-future-3' => [
                'linkText' => 'One Simple Trick to Protect Your Family&rsquo;s Future',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            '1-simple-trick-to-10-per-month-life-insurance-2' => [
                'linkText' => '1 Simple Trick to &pound;10 per month Life Insurance',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            '1-simple-trick-to-10-per-month-life-insurance-3' => [
                'linkText' => '1 Simple Trick to &pound;10 per month Life Insurance',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            'new-policy-in-the-uk-simple-trick-to-save-your-family-thousands-2' => [
                'linkText' => 'New Policy in the UK: Simple Trick to Save Your Family Thousands',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            'new-policy-in-the-uk-simple-trick-to-save-your-family-thousands-3' => [
                'linkText' => 'New Policy in the UK: Simple Trick to Save Your Family Thousands',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            'new-policy-in-the-uk-if-you-dont-have-life-insurance-you-better-read-this-2' => [
                'linkText' => 'New Policy in UK – If you Don&rsquo;t Have Life Insurance You Better Read This&hellip;',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
            'new-policy-in-the-uk-if-you-dont-have-life-insurance-you-better-read-this-3' => [
                'linkText' => 'New Policy in UK – If you Don&rsquo;t Have Life Insurance You Better Read This&hellip;',
                'date' => '',
                'trackingCode' => '',
                'category' => 'finance',
                'thumbnail' => false,
            ],
        ],
    ],
];
