<div class="comments">
    <hr>
    <p><strong>Comments (6)</strong></p>
            <div class="row">
                <div class="small-2 large-1 columns">
                    <img src="/images/comments/woman.png">
                </div>
                <div class="small-10 large-11 columns">
                    <strong>Susan D.</strong> wrote:<br>
                    Never heard of this plan before, thanks for the information. I went through your form and worked with a really helpful person to get my insurance. My payments are actually manageable now!
                </div>
            </div>
            <div class="row">
                <div class="small-2 large-1 columns">
                    <img src="/images/comments/familybeach.png">
                </div>
                <div class="small-10 large-11 columns">
                    <strong>Paul C.</strong> wrote:<br>
                    Didn&rsquo;t qualify for life insurance when I first applied. I reapplied a couple months ago after hearing the guidelines were relaxed, and I was eligible! Happy to be putting the extra money we&rsquo;re saving into my kid&rsquo;s college fund.
                </div>
            </div>
            <div class="row">
                <div class="small-2 large-1 columns">
                    <img src="/images/comments/personicon.gif">
                </div>
                <div class="small-10 large-11 columns">
                    <strong>Kevin L.</strong> wrote:<br>
                    I Got &pound;115,000 Life Insurance for &pound;10/Month With This Ridiculously Easy Trick! Just Go <a href="<?php echo $this->referralLink()->createLink($this->trackingCode, $this->subId); ?>" rel="external">Here</a>
                </div>
            </div>
            <div class="row">
                <div class="small-2 large-1 columns">
                    <img src="/images/comments/manwaterski.png">
                </div>
                <div class="small-10 large-11 columns">
                    <strong>Richard B.</strong> wrote:<br>
                    is this a scam?
                </div>
            </div>
            <div class="row">
                <div class="small-2 large-1 columns">
                    <img src="/images/comments/bman.png">
                </div>
                <div class="small-10 large-11 columns">
                    <strong>Daryl J.</strong> wrote:<br>
                    @Richard Thought it was a scam too at first like it was too good to be true but I filled the form out anyway and signed up for the &pound;10/month plan. It was really easy actually and I&rsquo;m not paying an arm and a leg anymore.
                </div>
            </div>
            <div class="row">
                <div class="small-2 large-1 columns">
                    <img src="/images/comments/personicon.gif">
                </div>
                <div class="small-10 large-11 columns">
                    <strong>Anonymous</strong> wrote:<br>
                    great article
                </div>
            </div>
        </table>
    <hr>
</div>
