<main class="article">
    <div class="row">
        <div class="large-12 show-for-large-up column text-right social-widgets">
            <?php echo $this->partial('money-saving-news/partial/social-includes'); ?>
        </div>
    </div>
    <div class="row">
        <div class="small-12 large-9 column">
            <section class="article-content">
                <h1>
                    15 Very Rare Photos From The Past That Will Blow Your Mind!
                </h1>
                <?php echo $this->partial('money-saving-news/partial/article-author', ['articleDate' => $this->articleDate, 'articleLinkText' => $this->articleLinkText]); ?>
                <p>
                    Some of these photos will leave you wondering what could have been, some will leave you thinking if they only knew, and some will just astonish you. It&rsquo;s amazing enough that it&rsquo;s rare, but what happened in these photos will leave you stunned.
                </p>
                <h3>
                    A priest praying over the victims of the Titanic (1912)
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/15-very-rare-photos-from-the-past/1.jpg" alt="A priest praying over the victims of the Titanic" />
                </p>
                <p>
                    This was taken on board of one of the body recovery ships that followed the tragic sinking of the Titanic. The mass funeral of the dozens of victims that were to be buried at sea. Out of the 306 passengers, only 166 bodies were retrieved.
                </p>
                <h3>
                    Filming of the MGM Opening Credits (1928)
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/15-very-rare-photos-from-the-past/2.jpg" alt="Filming of the MGM Opening Credits" />
                </p>
                <p>
                    Yes, that is the lion that we see in the opening credits for every movie MGM ever made. It&rsquo;s still a wonder how those other titles and transitions were made back then when people were just putting sound into their movies. It was a more tedious kind of work back then unlike today&rsquo;s digital age, where we can make opening credits in a matter of minutes.
                </p>
                <h3>
                    Hitler, Speer, and the Schwerer Gustav (1941)
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/15-very-rare-photos-from-the-past/3.jpg" alt="Hitler, Speer, and The Schwerer Gustav" />
                </p>
                <p>
                    World War II was one of the biggest events in the history of the world, caused by the conflicts between the Allied Forces and the Axis Powers. Being the most widespread war, over a hundred million lives were lost. The Schwerer Gustav is one of the largest pieces of artillery that was ever used in combat. And you guessed it, if Hitler saw it, you&rsquo;d know it&rsquo;s one of theirs. And here they are, perhaps admiring the structure of this killing machine.
                </p>
                <h3>
                    The First Selfie Ever Taken (1839)
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/15-very-rare-photos-from-the-past/4.jpg" alt="The First Selfie Ever Taken" />
                </p>
                <p>
                    The man who took this photo is named Robert Cornelius, and it was outside the store that his family owned. And thus, it is known to be the first self-portrait, or in our modern lingo, the first selfie ever taken. If Robert Cornelius was still alive today, he probably didn&rsquo;t expect for this to be a trend in photo taking.
                </p>
                <h3>
                    People Posing Next to the Face of the Statue of Liberty (1886)
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/15-very-rare-photos-from-the-past/5.jpg" alt="People Posing Next to the Face of the Statue of Liberty" />
                </p>
                <p>
                    While no one can probably get to the face of the Statue of Liberty and take a picture now, these two, most likely mother and son, were lucky enough to get to it while the statue was still in construction. It&rsquo;s cool if you think about it, and they probably ended up talking about that moment for the rest of their lives back then, with this photo as proof.
                </p>
                <h3>
                    Little Nap (1915)
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/15-very-rare-photos-from-the-past/6.jpg" alt="Little Nap" />
                </p>
                <p>
                    Ah, this cute little chimp. Little Nap was a popular tourist attraction in 1915, and judging from his costume, he was also known as the &ldquo;Napoleon of the Chimpanzee World&rdquo;. We&rsquo;re wondering if it&rsquo;s also because of his size, or his ability to be able to conquer the hearts of tourists passing by, stopping to take photographs and watch him do what he does. But it&rsquo;s still cute to see a chimpanzee dressed so elegantly.
                </p>
                <h3>
                    Racing Cars on the Roof of the Fiat Factory in Italy (1923)
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/15-very-rare-photos-from-the-past/7.jpg" alt="Racing Cars on the Roof of the Fiat Factory in Italy" />
                </p>
                <p>
                    As dangerous as this seems, this was apparently a thing back then. It goes to show how wide the span of the roof, or perhaps the whole building was at that time; a building that had housed the Fiat automobile factory, so maybe it makes a little more sense as to why there are race cars above.
                </p>
                <p>
                    The roof also served as a test track too. Hopefully no one swerved and fell off the roof, right?
                </p>
                <h3>
                    Woman Caught Mid-Sneeze (1900)
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/15-very-rare-photos-from-the-past/8.jpg" alt="Woman Caught Mid-Sneeze" />
                </p>
                <p>
                    Isn&rsquo;t this funny? The woman probably didn&rsquo;t know the camera took her photo as she was about to do that. This photo probably gave her an embarrassingly funny memory. We can just hope that she really sneezed, because half sneezes can be awful and very frustrating.
                </p>
                <h3>
                    Queenie, the Surfing Elephant (1950)
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/15-very-rare-photos-from-the-past/9.jpg" alt="Queenie, the Surfing Elephant" />
                </p>
                <p>
                    Now this is a sight to see. Queenie is the very first surfing elephant! It would have been fun to surf with her, provided she didn&rsquo;t crash. Queenie looks to be handling her surfboard quite well, so she probably could have made a real career out of this. As well, surfing with an elephant would have been quite the novelty. 
                </p>
                <h3>
                    PanAm Transporting a 5mb Hard Drive (1956)
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/15-very-rare-photos-from-the-past/10.jpg" alt="PanAm Transporting a 5MB Hard Drive" />
                </p>
                <p>
                    Technology today allows us to have hard drives reaching up to 2 Terabytes, which can easily fit in the pocket of your jacket. Apparently, back in the 50&rsquo;s, you would have needed a pretty big pocket to carry a mere 5mb hard drive. Just imagine carrying this large, heavy hard drive around with you all day. Not exactly the most portable computer in the world, is it? 
                </p>
                <p>
                    It is photos such as this that remind you just how far we have come in the technology field. 
                </p>
                <h3>
                    Walking Machine (1937)
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/15-very-rare-photos-from-the-past/11.jpg" alt="Walking Machine" />
                </p>
                <p>
                    Now, at first, you may be wondering why in the world would you need a walking machine? Well, if you are a shoe manufacturer, this machine would have been a massive breakthrough as it can easily test the durability of all your shoes. It is way better than putting on the shoes yourself and walking around for hours on end. 
                </p>
                <h3>
                    First International Wimbledon Match (1883)
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/15-very-rare-photos-from-the-past/12.jpg" alt="First International Wimbledon Match" />
                </p>
                <p>
                    It was between W. and E. Renshaw from London and C.M and J.S Clark from the U.S.A. It was at a time when tennis shorts weren&rsquo;t in style, or weren&rsquo;t invented yet. Hopefully nothing ripped as they were running across the court.
                </p>
                <h3>
                    Human Pinsetters (1914)
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/15-very-rare-photos-from-the-past/13.jpg" alt="Human Pinsetters" />
                </p>
                <p>
                    Back in the good old days, when bowling lanes didn&rsquo;t quite have the automatic pin setters like we do in modern times, young boys were in charge of putting the fallen pins away and setting everything back up. 
                </p>
                <h3>
                    Beauty Pageant Winners (1922)
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/15-very-rare-photos-from-the-past/14.jpg" alt="Beauty Pageant Winners" />
                </p>
                <p>
                    We can all agree that the standards of beauty back then were much different. As seen here in this photo, so was the fashion and the hair. With that said, history has a way of repeating itself so you could probably get away with a similar hairstyle in this day and age.
                </p>
                <h3>
                     Couple on a Zipline (1923)
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/15-very-rare-photos-from-the-past/15.jpg" alt="Couple on a Zipline" />
                </p>
                <p>
                    Unlike today where the zip lines are at really high heights for us to enjoy the views beneath us, the zip lines back then were lower. This couple seemed to be enjoying their ride a lot and I am sure it was an effective means of travel.
                </p>
            </section>
            <?php echo $this->partial('money-saving-news/partial/more-to-explore'); ?>
        </div>
        <div class="small-12 large-3 column">
            <div class="trending">
                <?php echo $this->partial('money-saving-news/partial/trending'); ?>
            </div>
            <div class="row">
                <div class="stocks-shares column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/stocks'); ?>
                </div>
                <div class="column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/banner/300x250', ['trackingCode' => $this->trackingCode, 'subId' => $this->subId]); ?>
                </div>
            </div>
        </div>
    </div>
</main>
