<main class="article">
    <div class="row">
        <div class="large-12 show-for-large-up column text-right social-widgets">
            <?php echo $this->partial('money-saving-news/partial/social-includes'); ?>
        </div>
    </div>
    <div class="row">
        <div class="small-12 large-9 column">
            <section class="article-content">
                <h1>
                    5 amazing hybrid animals
                </h1>
                <?php echo $this->partial('money-saving-news/partial/article-author', ['articleDate' => $this->articleDate, 'articleLinkText' => $this->articleLinkText]); ?>
                <p>
                    1. Zebroid
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/5-amazing-hybrid-animals/1.jpg" />
                    Image source: <a href="https://commons.wikimedia.org/wiki/File:Zeedonk_800.jpg" rel="external">https://commons.wikimedia.org/wiki/File:Zeedonk_800.jpg</a>
                </p>
                <p>
                    This may seem unreal, but the zebroid (or zorse, zebra mule or zonkey) is a genuine cross between a zebra and an equine! The zebroid is the offspring of a zebra stallion and a female equine. This fascinating animal has been bred since the 19th century with geologist Charles Darwin making reference to them in his works!
                </p>
                <p>
                    2. Liger
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/5-amazing-hybrid-animals/2.jpg" />
                    Image source: <a href="https://commons.wikimedia.org/wiki/File:Liger_couple.jpg" rel="external">https://commons.wikimedia.org/wiki/File:Liger_couple.jpg</a>
                </p>
                <p>
                    A cross between a male lion and a female tiger, the liger is thought to be the largest of all known felines! They exist only in captivity, and ligers often grow to be larger in size than either parent species. Sadly most ligers suffer from genetic disorders and are often unable to produce offspring.
                </p>
                <p>
                    3. Pizzly bear
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/5-amazing-hybrid-animals/3.jpg" />
                    Image source: <a href="http://likes.com/weird/15-unbelievable-hybrid-animals?page=11" rel="external">http://likes.com/weird/15-unbelievable-hybrid-animals?page=11</a>
                </p>
                <p>
                    Also known as a grolar bear, this is a very rare hybrid that has been seen in captivity and in the wild, this bear is a result of a polar and grizzly bear mating. The first discovery of a pizzly bear was in 2006, when a hunter shot what he thought was a polar bear, only to discover that it was a hybrid with a polar bear mother and grizzly bear father.
                </p>
                <p>
                    4. Wholphin
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/5-amazing-hybrid-animals/4.jpg" />
                    Image source: <a href="https://www.flickr.com/photos/smsea/5370756835" rel="external">https://www.flickr.com/photos/smsea/5370756835</a>
                </p>
                <p>
                    The wholphin is slightly misleading, in that it is a mixture of a false killer whale and the bottlenose dolphin. The false killer whale is scientifically a member of the dolphin family, so this &ldquo;hybrid&rdquo; is more realistic than others. However, the species is extremely rare, with the oldest known wholphin being born in captivity in Hawaii.
                </p>
                <p>
                    5. Cama
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/5-amazing-hybrid-animals/5.jpg" />
                    Image source: <a href="https://www.flickr.com/photos/craigwright/4180228237/in/album-72157622865416813/" rel="external">https://www.flickr.com/photos/craigwright/4180228237/in/album-72157622865416813/</a>
                </p>
                <p>
                    The cama is the result of breeding between Asian camels and South American Llamas. They were first created through artificial insemination and the resulting animal is the size of a camal, with the males attracted to femal llamas.
                </p>
            </section>
            <?php echo $this->partial('money-saving-news/partial/more-to-explore'); ?>
        </div>
        <div class="small-12 large-3 column">
            <div class="trending">
                <?php echo $this->partial('money-saving-news/partial/trending'); ?>
            </div>
            <div class="row">
                <div class="stocks-shares column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/stocks'); ?>
                </div>
                <div class="column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/banner/300x250', ['trackingCode' => $this->trackingCode, 'subId' => $this->subId]); ?>
                </div>
            </div>
        </div>
    </div>
</main>
