<main class="article">
    <div class="row">
        <div class="large-12 show-for-large-up column text-right social-widgets">
            <?php echo $this->partial('money-saving-news/partial/social-includes'); ?>
        </div>
    </div>
    <div class="row">
        <div class="small-12 large-9 column">
            <section class="article-content">
                <h1>
                    5 things that were invented by accident!
                </h1>
                <?php echo $this->partial('money-saving-news/partial/article-author', ['articleDate' => $this->articleDate, 'articleLinkText' => $this->articleLinkText]); ?>
                <h3>
                    Fireworks
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/5-things-that-were-invented-by-accident/1.jpg" alt="Fireworks" />
                </p>
                <p>
                    Believe it or not, fireworks were a happy culinary accident. About 2,000 years ago in China, a cook mixed three common kitchen denizens over a hot stove. Those were charcoal, sulphur, and what we now know as potassium nitrate. The chemists reading will probably already have guessed what happened when flame was applied to this mixture! The cook must have gotten quite a shock when their newly-formulated gunpowder exploded with a loud bang. Understandably, the Chinese were absolutely fascinated with what they decided to call &ldquo;huo yao,&rdquo; or &ldquo;fire chemical.&rdquo; After some experimentation, it was discovered that a little huo yao in a hollow tube could blow the entire tube to smithereens. Thus was born the firecracker, which remains a staple of celebration to this day.
                </p>
                <h3>
                    LSD
                </h3>
                <p class="text-center">
                    <img src="/images/article/5-things-that-were-invented-by-accident/2.jpg" alt="LSD" />
                </p>
                <p>
                    In 1948, a Swiss researcher named Albert Hofmann was conducting some routine experiments on the active chemical in the wheat fungus known as ergot. He was looking for a stimulant for the circulatory system, but the going was slow. At some point in his experimentation, he accidentally got some of the chemical he was testing, Lysergic Acid Diathylamide, on his fingertips. Oh well, he probably thought. Not like its dangerous or anything. A few hours later, he started to feel dizzy and had to lie down. A few LSD trips later, he realized he&rsquo;d stumbled onto something truly significant.
                </p>
                <h3>
                    Microwaves
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/5-things-that-were-invented-by-accident/3.jpg" alt="Microwaves" />
                </p>
                <p>
                     Back when electricity was new, anyone who read up about it was considered an expert. Percy Spencer fell into this category. An orphan with little formal education, he taught himself about electricity, then about radio technology, then about chemistry, physics, mathematics, calculus, and metallurgy, just for fun. Spencer became so highly regarded that he ended up as a contractor working on magnetrons for the government. It was then that he noticed that the candy bar in his pocket melted whenever he stood in front of an active radar set. After some experimentation, he and his colleagues were able to pop popcorn, explode an egg, and perform other tricks that anyone with a modern microwave will recognise.
                </p>
                <h3>
                    Penicillin
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/5-things-that-were-invented-by-accident/4.jpg" alt="Penicillin" />
                </p>
                <p>
                     If there&rsquo;s any proof out there that laziness can be a good thing, let this story be it. Sir Alexander Fleming was a chemical researcher experimenting with the flu virus in 1928. He carelessly contaminated a petri dish containing streptococcus bacteria right before leaving on a two week vacation. It&rsquo;s easy to imagine this scenario going very, very wrong – after all, the man was working with some pretty scary germs – but when he returned, he noticed that the mould that had grown on his experiment was preventing the development of bacteria in the culture dishes. Fleming had discovered the world&rsquo;s first antibiotic.
                </p>
                <h3>
                    Silly Putty
                </h3>
                <p class="image-full-width">
                    <img src="/images/article/5-things-that-were-invented-by-accident/5.jpg" alt="Silly Putty" />
                </p>
                <p>
                     World War II was a bad time to need rubber. Japan had strategically snapped up all of the major rubber producers in the world at that time, making the one ingredient available for tires and gas masks completely unavailable to the Allies. Research into synthetic rubber was so hot that nobody&rsquo;s completely sure who came up with Silly Putty first. At the time, it was discarded as a rubber substitute because&hellip; well, have you ever played with Silly Putty? Nevertheless, it was a cool chemical: nontoxic, bounced like a ball, shattered if struck, flowed like a liquid, and was hand-mouldable, and surely it had to be good for something.
                <p>
                     It wasn&rsquo;t. But it became so popular in the post-war years that it even went to space on Apollo 8. Not bad for a mistake!
                </p>
            </section>
            <?php echo $this->partial('money-saving-news/partial/more-to-explore'); ?>
        </div>
        <div class="small-12 large-3 column">
            <div class="trending">
                <?php echo $this->partial('money-saving-news/partial/trending'); ?>
            </div>
            <div class="row">
                <div class="stocks-shares column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/stocks'); ?>
                </div>
                <div class="column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/banner/300x250', ['trackingCode' => $this->trackingCode, 'subId' => $this->subId]); ?>
                </div>
            </div>
        </div>
    </div>
</main>
