<main class="article">
    <div class="row">
        <div class="large-12 show-for-large-up column text-right social-widgets">
            <?php echo $this->partial('money-saving-news/partial/social-includes'); ?>
        </div>
    </div>
    <div class="row">
        <div class="small-12 large-9 column">
            <section class="article-content">
                <h1>
                    7 of the craziest insurance policies
                </h1>
                <?php echo $this->partial('money-saving-news/partial/article-author', ['articleDate' => $this->articleDate, 'articleLinkText' => $this->articleLinkText]); ?>
                <p>
                    Insuring your car or mobile phone might seem like second nature to most of us, but how about taking out a policy for your legs or maybe your smile?!
                </p>
                <p>
                    Crazy as it may seem, celebrities have been insuring various body parts for years – well, if you make a living as a footballer, you can&rsquo;t really do much with a dodgy leg!
                </p>
                <h3>
                    Tongue
                </h3>
                <p>
                    Rock God <strong>Gene Simmons</strong> insured his extraordinarily long tongue (measured at over 7 inches) for a cool &#36;1 million at the height of KISS&rsquo; fame. Part of Simmons&rsquo; stage performance involves wiggling his famous tongue at the audience – and the show would be nothing if something happened to it. Right?!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/7-of-the-craziest-insurance-policies/1.jpg" alt="Gene Simmons Tongue" />
                    Image source: <a href="http://www.peanutmom.com/2013/world-war-food.php" rel="external">http://www.peanutmom.com/2013/world-war-food.php</a>
                </p>
                <h3>
                    Feet and Toes
                </h3>
                <p>
                    World famous footballer <strong>David Beckham</strong> reportedly took out insurance on his legs, feet and toes for &#36;195 million! His ludicrous policy protects him against injury and disfigurements – well, you wouldn&rsquo;t want to see his broken toe in a Calvin Klein advert would you?
                </p>
                <h3>
                    Smile
                </h3>
                <p>
                    <strong>Julia Roberts</strong> has one of the most famous smiles in Hollywood, but does her career depend on it? She seems to think so; with a toothy grin worth approximately &#36;30 million!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/7-of-the-craziest-insurance-policies/2.jpg" alt="Julia Roberts Smile" />
                    Image source: <a href="http://www.fanpop.com/clubs/julia-roberts/images/742729/title/julia-roberts-wallpaper" rel="external">http://www.fanpop.com/clubs/julia-roberts/images/742729/title/julia-roberts-wallpaper</a>
                </p>
                <h3>
                    Voice
                </h3>
                <p>
                    The Boss (aka <strong>Bruce Springsteen</strong>) would have nothing to worry about should he lose his voice – his &#36;6 million policy will surely cover any loss of earnings!
                </p>
                <h3>
                    Legs
                </h3>
                <p>
                    If you earn your money as a super model, you need your legs in tip-top condition, which is why <strong>Heidi Klum</strong> has hers covered for &#36;1 million – each! But that&rsquo;s nothing compared to the policy Gillette took out to cover <strong>Mariah Carey</strong>&rsquo;s pins - &#36;1 billion! Yes, &#36;1 billion! Wow!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/7-of-the-craziest-insurance-policies/3.jpg" alt="Mariah Carey’s Legs" />
                    Image source: <a href="http://www.hdevinnvisual.com/product-presentations/gillette-venus-mariah-carey-legs-of-a-goddess-contest-at-the-radio-city-music-hall-ii" rel="external">http://www.hdevinnvisual.com/product-presentations/gillette-venus-mariah-carey-legs-of-a-goddess-contest-at-the-radio-city-music-hall-ii</a>
                </p>
                <h3>
                    Hands
                </h3>
                <p>
                    Rolling Stone guitarist <strong>Keith Richards</strong> takes care of his hands with a policy worth a reported &#36;2 million, a fairly low sum compared to <strong>Jeff Beck&rsquo;s</strong> &#36;7 million for his own digits!
                </p>
                <h3>
                    Breasts
                </h3>
                <p>
                    <strong>Dolly Parton</strong>, <strong>Holly Madison</strong> and <strong>Madonna</strong> have all insured their breasts; Dolly for &#36;600,000, Holly for &#36;1 million and Madonna is covered for &#36;2 million – hey, image is everything in this business we call &lsquo;show&rsquo;!
                </p>
            </section>
            <?php echo $this->partial('money-saving-news/partial/more-to-explore'); ?>
        </div>
        <div class="small-12 large-3 column">
            <div class="trending">
                <?php echo $this->partial('money-saving-news/partial/trending'); ?>
            </div>
            <div class="row">
                <div class="stocks-shares column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/stocks'); ?>
                </div>
                <div class="column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/banner/300x250', ['trackingCode' => $this->trackingCode, 'subId' => $this->subId]); ?>
                </div>
            </div>
        </div>
    </div>
</main>
