<main class="article">
    <div class="row">
        <div class="large-12 show-for-large-up column text-right social-widgets">
            <?php echo $this->partial('money-saving-news/partial/social-includes'); ?>
        </div>
    </div>
    <div class="row">
        <div class="small-12 large-9 column">
            <section class="article-content">
                <h1>
                    9 genius life hacks you didn&rsquo;t know you needed
                </h1>
                <?php echo $this->partial('money-saving-news/partial/article-author', ['articleDate' => $this->articleDate, 'articleLinkText' => $this->articleLinkText]); ?>
                <p>
                    1. Tired of getting sticky hands every time you have an ice lolly? Push the lolly stick through a cupcake wrapper – problem solved!
                </p>
                <p class="image-source text-center">
                    <img src="/images/article/9-genius-life-hacks-you-didnt-know-you-needed/1.jpg" />
                    Image source: <a href="http://www.snappypixels.com/genius-ideas/wrong-life-hacks-17-pics" rel="external">http://www.snappypixels.com/genius-ideas/wrong-life-hacks-17-pics</a>
                </p>
                <p>
                    2. If you like strawberries, chances are you’ve been eating them wrong! With just a straw, you can enjoy the whole fruit and none of the stem!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/9-genius-life-hacks-you-didnt-know-you-needed/2.jpg" />
                    Image source: <a href="http://www.lifehacker.co.in/jugaad/How-To-Remove-The-Stem-Of-Strawberries-Without-Cutting-Them-Off/articleshow/35729990.cms" rel="external">http://www.lifehacker.co.in/jugaad/How-To-Remove-The-Stem-Of-Strawberries-Without-Cutting-Them-Off/articleshow/35729990.cms</a>
                </p>
                <p>
                    3. Tired of hunting for your suitcase at baggage claim? Not anymore!
                </p>
                <p class="image-source text-center">
                    <img src="/images/article/9-genius-life-hacks-you-didnt-know-you-needed/3.jpg" />
                    Image source: <a href="http://www.lifehack.org/articles/lifestyle/100-life-hacks-that-make-life-easier.html" rel="external">http://www.lifehack.org/articles/lifestyle/100-life-hacks-that-make-life-easier.html</a>
                </p>
                <p>
                    4. Ever wondered what the whole in the ring pull was for? Well now you know!
                </p>
                <p class="image-source text-center">
                    <img src="/images/article/9-genius-life-hacks-you-didnt-know-you-needed/4.jpg" />
                    Image source: <a href="http://twistedsifter.com/2013/01/50-life-hacks-to-simplify-your-world" rel="external">http://twistedsifter.com/2013/01/50-life-hacks-to-simplify-your-world</a>
                </p>
                <p>
                    5. Never get confused by your keys again! Colour co-ordinate them with different nail varnishes!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/9-genius-life-hacks-you-didnt-know-you-needed/5.jpg" />
                    Image source: <a href="http://www.hackthelife.net/self-improvements/top-25-girls-life-hacks" rel="external">http://www.hackthelife.net/self-improvements/top-25-girls-life-hacks</a>
                </p>
                <p>
                    6.  Avoid banging your fingers when hammering with this smart trick
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/9-genius-life-hacks-you-didnt-know-you-needed/6.jpg" />
                    Image source: <a href="http://www.lifehack.org/articles/lifestyle/100-life-hacks-that-make-life-easier.html" rel="external">http://www.lifehack.org/articles/lifestyle/100-life-hacks-that-make-life-easier.html</a>
                </p>
                <p>
                    7. Stop your tights from running with a dab of clear nail varnish
                </p>
                <p class="image-source text-center">
                    <img src="/images/article/9-genius-life-hacks-you-didnt-know-you-needed/7.jpg" />
                    Image source: <a href="http://www.cosmopolitan.com/style-beauty/fashion/how-to/a29466/genius-hacks-for-fixing-ruined-clothes" rel="external">http://www.cosmopolitan.com/style-beauty/fashion/how-to/a29466/genius-hacks-for-fixing-ruined-clothes</a>
                </p>
                <p>
                    8.  Never lose your cables again!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/9-genius-life-hacks-you-didnt-know-you-needed/8.jpg" />
                    Image source: <a href="http://www.lifehack.org/articles/lifestyle/100-life-hacks-that-make-life-easier.html" rel="external">http://www.lifehack.org/articles/lifestyle/100-life-hacks-that-make-life-easier.html</a>
                </p>
                <p>
                    9. Cut down on your clean up time!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/9-genius-life-hacks-you-didnt-know-you-needed/9.jpg" />
                    Image source: <a href="http://twistedsifter.com/2013/01/50-life-hacks-to-simplify-your-world" rel="external">http://twistedsifter.com/2013/01/50-life-hacks-to-simplify-your-world</a>
                </p>
            </section>
            <?php echo $this->partial('money-saving-news/partial/more-to-explore'); ?>
        </div>
        <div class="small-12 large-3 column">
            <div class="trending">
                <?php echo $this->partial('money-saving-news/partial/trending'); ?>
            </div>
            <div class="row">
                <div class="stocks-shares column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/stocks'); ?>
                </div>
                <div class="column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/banner/300x250', ['trackingCode' => $this->trackingCode, 'subId' => $this->subId]); ?>
                </div>
            </div>
        </div>
    </div>
</main>
