<main class="article">
    <div class="row">
        <div class="large-12 show-for-large-up column text-right social-widgets">
            <?php echo $this->partial('money-saving-news/partial/social-includes'); ?>
        </div>
    </div>
    <div class="row">
        <div class="small-12 large-9 column">
            <section class="article-content">
                <h1>
                    Crazy pictures that will blow you away! Number 5 had me floored!
                </h1>
                <?php echo $this->partial('money-saving-news/partial/article-author', ['articleDate' => $this->articleDate, 'articleLinkText' => $this->articleLinkText]); ?>
                <p>
                    They say a picture speaks a thousand words, so let these images speak for themselves!
                </p>
                <p>
                    1. This famous shot of the train at Gare Montparnasse, Paris was taken on 22nd October 1895. Incredibly, there was only one fatality in this crash; a woman standing in the street below who was killed by falling masonry.
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/crazy-pictures-that-will-blow-you-away-number-5-had-me-floored/1.jpg" />
                    Image source: <a href="https://en.wikipedia.org/wiki/Montparnasse_derailment#/media/File:Train_wreck_at_Montparnasse_1895.jpg" rel="external">https://en.wikipedia.org/wiki/Montparnasse_derailment#/media/File:Train_wreck_at_Montparnasse_1895.jpg</a>
                </p>
                <p>
                    2. The Great Sphinx of Giza is a limestone statue, standing in the west bank of the Nile in Egypt. Egyptologists widely believe the statue was built 2500 BC to represent the face of Pharaoh Khafra. Years ago, tourists were permitted to climb all over the statue!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/crazy-pictures-that-will-blow-you-away-number-5-had-me-floored/2.jpg" />
                    Image source: <a href="http://thechive.com/2012/05/15/your-mind-officially-blown-33-photos/" rel="external">http://thechive.com/2012/05/15/your-mind-officially-blown-33-photos/</a>
                </p>
                <p>
                    3. La tour Eiffel was erected in 1889, and continues to be a world famous tourist attraction, bringing approximately 25,000 people to the top of the tower every day! Check out this alternative view which you might not have seen before!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/crazy-pictures-that-will-blow-you-away-number-5-had-me-floored/3.jpg" />
                    Image source: <a href="http://thechive.com/2012/05/15/your-mind-officially-blown-33-photos/" rel="external">http://thechive.com/2012/05/15/your-mind-officially-blown-33-photos/</a>
                </p>
                <p>
                    4. We&rsquo;ve all had that awkward moment when our <em>bae</em> takes pictures of us &ldquo;sleeping&rsquo; only to realise that the mirror behind us gave the game away!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/crazy-pictures-that-will-blow-you-away-number-5-had-me-floored/4.jpg" />
                    Image source: <a href="http://www.brainjet.com/random/6412/15-photos-guaranteed-to-make-you-laugh-every-time#slide/0" rel="external">http://www.brainjet.com/random/6412/15-photos-guaranteed-to-make-you-laugh-every-time#slide/0</a>
                </p>
                <p>
                    5. Lee Redmond began growing her fingernails in 1979 and currently holds the world record for the longest fingernails (female) EVER! They reach a mindblowing length of 8.65m! Imagine trying to brush your hair or do the dishes with these!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/crazy-pictures-that-will-blow-you-away-number-5-had-me-floored/5.jpg" />
                    Image source: <a href="http://www.guinnessworldrecords.cn/world-records/extraordinary/longest-fingernails-%28female%29-ever" rel="external">http://www.guinnessworldrecords.cn/world-records/extraordinary/longest-fingernails-%28female%29-ever</a>
                </p>
                <p>
                    6. This tiny little guy is only 10mm in length and can be found in Cuba! The Monte Iberia Eleuth was only recently discovered – and you can tell why; based on how small they are!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/crazy-pictures-that-will-blow-you-away-number-5-had-me-floored/6.jpg" />
                    Image source: <a href="http://trends-addict.com/worlds-20-smallest-animals/" rel="external">http://trends-addict.com/worlds-20-smallest-animals/</a>
                </p>
                <p>
                    7. The greatest photobomb of all time? This crazy squirrel got in on the action of a couple&rsquo;s photo in Banff National Park in Alberta, Canada. Just brilliant!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/crazy-pictures-that-will-blow-you-away-number-5-had-me-floored/7.jpg" />
                    Image source: <a href="http://intelligenttravel.nationalgeographic.com/2009/08/12/ground_squirrel_photo_crasher/" rel="external">http://intelligenttravel.nationalgeographic.com/2009/08/12/ground_squirrel_photo_crasher/</a>
                </p>
            </section>
            <?php echo $this->partial('money-saving-news/partial/more-to-explore'); ?>
        </div>
        <div class="small-12 large-3 column">
            <div class="trending">
                <?php echo $this->partial('money-saving-news/partial/trending'); ?>
            </div>
            <div class="row">
                <div class="stocks-shares column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/stocks'); ?>
                </div>
                <div class="column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/banner/300x250', ['trackingCode' => $this->trackingCode, 'subId' => $this->subId]); ?>
                </div>
            </div>
        </div>
    </div>
</main>
