<main class="article">
    <div class="row">
        <div class="large-12 show-for-large-up column text-right social-widgets">
            <?php echo $this->partial('money-saving-news/partial/social-includes'); ?>
        </div>
    </div>
    <div class="row">
        <div class="small-12 large-9 column">
            <section class="article-content">
                <h1>
                    She invited him back to her house – but he wasn&rsquo;t expecting this!
                </h1>
                <p>
                    Secretary invites married man back to her house. Then this happens.
                </p>
                <?php echo $this->partial('money-saving-news/partial/article-author', ['articleDate' => $this->articleDate, 'articleLinkText' => $this->articleLinkText]); ?>
                <p>
                    Last week was my 40th birthday and I really didn&rsquo;t feel like waking up that morning. I managed to pull myself together and go downstairs for breakfast, hoping my wife would be pleasant and say, &ldquo;Happy Birthday!&rdquo;, and possibly have a small present for me. As it turned out, she barely said good morning, let alone &ldquo;Happy Birthday&rdquo;. I thought&hellip; Well, that&rsquo;s marriage for you, but the kids&hellip; They will remember.
                </p>
                <p>
                    My kids came trampling down the stairs to breakfast, ate their breakfast, and didn&rsquo;t say a word to me. So when I made it out of the house and started for work, I felt pretty dumpy and despondent.
                </p>
                <p>
                    As I walked into my ofﬁce, my secretary Joanne said, &ldquo;Good Morning Boss, and by the way Happy Birthday!&rdquo;. It felt a bit better knowing that at least someone remembered. I worked in a zombie like fashion until about one o&rsquo;clock, when Joanne knocked on my door and said, &ldquo;You know, it&rsquo;s such a beautiful day outside, and it&rsquo;s your Birthday, why don&rsquo;t we go out for lunch, just you and me.&rdquo; I said, &ldquo;Thanks, Joanne, that&rsquo;s the best thing I&rsquo;ve heard all day. Let&rsquo;s go!&rdquo;.
                </p>
                <p>
                    We went to lunch but not where we&rsquo;d normally go. Instead she took me to a quiet bistro with a private table. We had a couple of mixed drinks and I enjoyed the meal tremendously. On the way back to the ofﬁce, Joanne said, &ldquo;You know, It&rsquo;s such a beautiful day&hellip; We don&rsquo;t have to go right back to the ofﬁce, do we?&rdquo; I replied with &ldquo;l suppose not. What do you have in mind?&rdquo; She said, &ldquo;Let&rsquo;s go to my apartment, it&rsquo;s just around the corner&rdquo;.
                </p>
                <p>
                    After arriving at her apartment, Joanne turned to me and said, &ldquo;Boss if you don&rsquo;t mind, I&rsquo;m going to step into the bedroom for just a moment. I&rsquo;ll be right back.&rdquo; &ldquo;Ok.&rdquo; I nervously replied. She went into the bedroom and, after a couple of minutes, she came out carrying a huge birthday cake&rdquo;. Followed by my wife, my kids, and dozens of my friends, and co-workers, all singing &ldquo;Happy Birthday&rdquo;.
                </p>
                <p>
                    And I just sat there&hellip;On the couch&hellip;
                </p>
                <p>
                    Naked.
                </p>
            </section>
            <?php echo $this->partial('money-saving-news/partial/more-to-explore'); ?>
        </div>
        <div class="small-12 large-3 column">
            <div class="trending">
                <?php echo $this->partial('money-saving-news/partial/trending'); ?>
            </div>
            <div class="row">
                <div class="stocks-shares column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/stocks'); ?>
                </div>
                <div class="column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/banner/300x250', ['trackingCode' => $this->trackingCode, 'subId' => $this->subId]); ?>
                </div>
            </div>
        </div>
    </div>
</main>
