<main class="article">
    <div class="row">
        <div class="large-12 show-for-large-up column text-right social-widgets">
            <?php echo $this->partial('money-saving-news/partial/social-includes'); ?>
        </div>
    </div>
    <div class="row">
        <div class="small-12 large-9 column">
            <section class="article-content">
                <h1>
                    Top 5 Mistakes when Buying Life Insurance
                </h1>
                <?php echo $this->partial('money-saving-news/partial/article-author', ['articleDate' => $this->articleDate, 'articleLinkText' => $this->articleLinkText]); ?>
                <p>
                    In a society where the tightening of purse strings means that essential cover like life insurance is often overlooked, it&rsquo;s important to understand the benefits of such a policy in the long-term. Unfortunately, the worst happens to us all at some point in our lives and for most people, loved ones will be left behind. Life insurance is a policy that helps to keep their futures safe and with policies from <strong>as little as &pound;5 a month</strong>*, protecting them won&rsquo;t break the bank either.
                </p>
                <p>
                    It&rsquo;s important that you learn from <strong>mistakes others have made</strong>, so that you don&rsquo;t make the same mistakes when taking out life insurance. Here are five of the <strong>biggest mistakes</strong> people make when buying life insurance.
                </p>
                <h3>
                    Mistake No. 1 – Buying too much cover
                </h3>
                <p>
                    Miscalculating your life insurance requirements can seriously affect what you pay each month. You may find that you <strong>pay too much</strong>, or too little, for what you actually need.
                </p>
                <p>
                    Choosing the right type of insurance is essential to guarantee the protection of your family once you&rsquo;re gone. For example, there&rsquo;s little point signing up for a decreasing term policy if you don&rsquo;t have a repayment mortgage to cover.
                </p>
                <p>
                    <a href="<?php echo $this->referralLink()->createLink($this->trackingCode, $this->subId); ?>" rel="external">Compare quotes online and view prices from 10 of the top UK insurers.</a> If you need any extra help, you can call us or we can call you.
                </p>
                <h3>
                    Mistake No. 2 - Believing the common misconceptions
                </h3>
                <p>
                    In the UK, <strong>67% of families don&rsquo;t have life insurance</strong>**. This whopping percentage is alarming, especially when you consider the families that will be left behind. In an industry that is tainted with mis-sold policies and misconceptions, it&rsquo;s essential that you trust the insurance provider and cover your life, and your loved ones futures, effectively.
                </p>
                <p>
                    Some people believe that life insurance won&rsquo;t pay out when in actual fact, <strong>98% of claims are paid out</strong>***. Others may think that the process is too complicated, or they haven&rsquo;t got time to fill in the endless reams of forms, when in actual fact, the process can be <strong>simple</strong> when done properly.
                </p>
                <p>
                    A major myth that needs to be quashed is the misguided &ldquo;it won&rsquo;t happen to me&rdquo; belief, when despite not wanting to think about it, it will happen eventually and life insurance should be there to cover you. It&rsquo;s a scary statistic but <strong>1 in 29 children will lose a parent before they finish full-time education</strong>**** – is it really worth the risk of going without a life insurance policy?
                <h3>
                    Mistake No. 3 - Lying on the application form
                </h3>
                <p>
                    This is a big no-no, even if you think that your insurer will never find out. It&rsquo;s crucial that you&rsquo;re truthful about your life because any inconsistency could lead to invalidation of your policy. Whether you&rsquo;re a smoker or you have a pre-existing health condition, you need to be completely honest, even if it means paying a little more each month. That way, your policy will remain valid, no matter what happens.
                </p>
                <h3>
                    Mistake No. 4 - Waiting too long to buy
                </h3>
                <p>
                    The younger you are, the <strong>cheaper a life insurance policy</strong> will be. Ideally, once you have settled down and have started to grow your family or you have a mortgage that ties you down, it&rsquo;s time to buy. The older, or unhealthier, that you become, the more expensive the policy will be. Starting the policy when you&rsquo;re young will help to keep your policy <strong>as affordable as possible</strong>.
                </p>
                <p>
                    It&rsquo;s easy to postpone the insurance but why put off what you can sort today? <a href="<?php echo $this->referralLink()->createLink($this->trackingCode, $this->subId); ?>" rel="external">Compare Life Cover Now</a>
                </p>
                <h3>
                    Mistake No. 5 - Not shopping around
                </h3>
                <p>
                    Being tempted by the latest life insurance advert on TV, or applying for a policy with your bank or familiar insurance provider, may be the way to go. Compare quotes from the top insurers and you will be able to see the various options available to you and choose the most ideal product for your circumstances.
                </p>
                <?php echo $this->partial('money-saving-news/partial/form/gender'); ?>
                <?php echo $this->partial('money-saving-news/partial/advertorial-disclaimer'); ?>
                <p class="disclaimers">
                    * Prices correct as of June 2015, quote is based on a 45-year old, non-smoker, with a level term policy over 20 years.
                </p>
                <p class="disclaimers">
                    ** Stats taken from Aviva Family Finance Report 2014
                </p>
                <p class="disclaimers">
                    *** 2014 Claims stats
                </p>
                <p class="disclaimers">
                    **** Source: Moneysavingexpert.com
                </p>
            </section>
        </div>
        <div class="small-12 large-3 column">
            <div class="trending">
                <?php echo $this->partial('money-saving-news/partial/trending'); ?>
            </div>
            <div class="row">
                <div class="stocks-shares column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/stocks'); ?>
                </div>
                <div class="column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/banner/300x250', ['trackingCode' => $this->trackingCode, 'subId' => $this->subId]); ?>
                </div>
            </div>
        </div>
    </div>
</main>

