<main class="article">
    <div class="row">
        <div class="large-12 show-for-large-up column text-right social-widgets">
            <?php echo $this->partial('money-saving-news/partial/social-includes'); ?>
        </div>
    </div>
    <div class="row">
        <div class="small-12 large-9 column">
            <section class="article-content">
                <h1>
                    You won&rsquo;t believe what&rsquo;s inside these cakes!
                </h1>
                <?php echo $this->partial('money-saving-news/partial/article-author', ['articleDate' => $this->articleDate, 'articleLinkText' => $this->articleLinkText]); ?>
                <p>
                    Surprise cakes are getting more popular by the day, with insane details inside that&rsquo;ll make your jaw drop!
                </p>
                <h3>
                    Engagement ring cake
                </h3>
                <p>
                    Looks like a normal white frosted cake, right? Just wait until you see what&rsquo;s inside!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/you-wont-believe-whats-inside-these-cakes/1.jpg" alt="Engagement ring cake" />
                    Image source: <a href="http://iambaker.net/baking-with-twin-cities-live/" rel="external">http://iambaker.net/baking-with-twin-cities-live/</a>
                </p>
                <p>
                    An engagement RING! How amazing would this proposal be?!
                </p>
                <h3>
                    Tie-dyed and numbered cake
                </h3>
                <p>
                    Looking for a wacky birthday cake? Not only is this cake tie dye, it&rsquo;s got an awesome surprise running through the middle!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/you-wont-believe-whats-inside-these-cakes/2.jpg" alt="Tie-dyed and numbered cake" />
                    Image source: <a href="http://www.tablespoon.com/recipes/rainbow-tie-dye-surprise-cake/15086094-ad54-4d4f-82b3-68bffd7a0c9a" rel="external">http://www.tablespoon.com/recipes/rainbow-tie-dye-surprise-cake/15086094-ad54-4d4f-82b3-68bffd7a0c9a</a>
                </p>
                <p>
                    Perfect for a 5<sup>th</sup> birthday party! And it can be customised for any number or occasion! 
                </p>
                <h3>
                    Secret Strawberry cake
                </h3>
                <p>
                    This strawberry-shaped cake looks impressive enough as it is, but cut it open for an extra treat; fresh strawberries!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/you-wont-believe-whats-inside-these-cakes/3.jpg" alt="Secret Strawberry cake" />
                    Image source: <a href="http://www.tablespoon.com/recipes/strawberry-surprise-cake/7c7256f6-8398-4e2a-bc62-692e6cdfee0e" rel="external">http://www.tablespoon.com/recipes/strawberry-surprise-cake/7c7256f6-8398-4e2a-bc62-692e6cdfee0e</a>
                </p>
                <h3>
                    Rainbow Skittle cake
                </h3>
                <p>
                    Anyone for Skittles? Taste the rainbow in this amazing colourful treat of cake and sweets!
                </p>
                <p class="image-source text-center">
                    <img src="/images/article/you-wont-believe-whats-inside-these-cakes/4.jpg" alt="Rainbow Skittle cake" />
                    Image source: <a href="http://www.sainsburysmagazine.co.uk/recipes/baking/special-occasion-cakes/item/surprise-skittles-rainbow-cake" rel="external">http://www.sainsburysmagazine.co.uk/recipes/baking/special-occasion-cakes/item/surprise-skittles-rainbow-cake</a>
                </p>
                <h3>
                    Zebra cake
                </h3>
                <p>
                    If you&rsquo;re a fan of animal print, then this cake is definitely for you! And it&rsquo;s so easy to make!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/you-wont-believe-whats-inside-these-cakes/5.jpg" alt="Zebra cake" />
                    Image source: <a href="http://www.healthyfoodnet.com/zebra-cake" rel="external">http://www.healthyfoodnet.com/zebra-cake</a>
                </p>
            </section>
            <?php echo $this->partial('money-saving-news/partial/more-to-explore'); ?>
        </div>
        <div class="small-12 large-3 column">
            <div class="trending">
                <?php echo $this->partial('money-saving-news/partial/trending'); ?>
            </div>
            <div class="row">
                <div class="stocks-shares column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/stocks'); ?>
                </div>
                <div class="column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/banner/300x250', ['trackingCode' => $this->trackingCode, 'subId' => $this->subId]); ?>
                </div>
            </div>
        </div>
    </div>
</main>
