<main class="article">
    <div class="row">
        <div class="large-12 show-for-large-up column text-right social-widgets">
            <?php echo $this->partial('money-saving-news/partial/social-includes'); ?>
        </div>
    </div>
    <div class="row">
        <div class="small-12 large-9 column">
            <section class="article-content">
                <h1>
                    You won&rsquo;t believe these trees actually exist!
                </h1>
                <?php echo $this->partial('money-saving-news/partial/article-author', ['articleDate' => $this->articleDate, 'articleLinkText' => $this->articleLinkText]); ?>
                <h3>
                    Chapel Oak, Seine-Maritime, France
                </h3>
                <p>
                    This ancient oak tree (estimated to be aged between 800 and 1,200 years old!) contains not one, but two chapels, built in 1669 after the tree was hit by a bolt of lightning. The village priest believed that the hollowing of the tree, as a result of the strike, was a holy act and thus the shrine and chapels were built.
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/you-wont-believe-these-trees-actually-exist/1.jpg" alt="Chapel Oak" />
                    Image source: <a href="http://www.wherecoolthingshappen.com/10-strangest-trees-on-earth/" rel="external">http://www.wherecoolthingshappen.com/10-strangest-trees-on-earth/</a>
                </p>
                <h3>
                    The Chandelier Tree, California, USA
                </h3>
                <p>
                    Located in Drive-Thru Tree Park, this 315 foot tall redwood has a hole cut through its base to let cars drive through!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/you-wont-believe-these-trees-actually-exist/2.jpg" alt="The Chandelier Tree" />
                    Image source: <a href="http://www.wherecoolthingshappen.com/10-strangest-trees-on-earth/" rel="external">http://www.wherecoolthingshappen.com/10-strangest-trees-on-earth/</a>
                </p>
                <h3>
                    Drago of Icod, Tenerife, Canary Islands
                </h3>
                <p>
                    Placed in the asparagus family, Dracaena draco is actually a tree-like plant. It was declared a National Monument in 1917, and is the largest of its kind in the World!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/you-wont-believe-these-trees-actually-exist/3.jpg" alt="Drago of Icod" />
                    Image source: <a href="http://www.wherecoolthingshappen.com/10-strangest-trees-on-earth/" rel="external">http://www.wherecoolthingshappen.com/10-strangest-trees-on-earth/</a>
                </p>
                <h3>
                    General Sherman, California, USA
                </h3>
                <p>
                    By volume, this giant sequoia tree is the largest known living single stem tree on Earth! 
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/you-wont-believe-these-trees-actually-exist/4.jpg" alt="General Sherman" />
                    Image source: <a href="http://dailytwocents.com/wp-content/uploads/2014/04/General_Sherman_tree_looking_up.jpg" rel="external">http://dailytwocents.com/wp-content/uploads/2014/04/General_Sherman_tree_looking_up.jpg</a>
                </p>
                <h3>
                    The Boab Prison Tree, Derby, Western Australia
                </h3>
                <p>
                    Believe it or not, this tree was apparently used as a holding cell for prisoners on their way to sentencing!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/you-wont-believe-these-trees-actually-exist/5.jpg" alt="The Boab Prison Tree" />
                    Image source: <a href="http://commons.wikimedia.org/wiki/File:Boab_Prison_Tree.jpg" rel="external">http://commons.wikimedia.org/wiki/File:Boab_Prison_Tree.jpg</a>
                </p>
            </section>
            <?php echo $this->partial('money-saving-news/partial/more-to-explore'); ?>
        </div>
        <div class="small-12 large-3 column">
            <div class="trending">
                <?php echo $this->partial('money-saving-news/partial/trending'); ?>
            </div>
            <div class="row">
                <div class="stocks-shares column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/stocks'); ?>
                </div>
                <div class="column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/banner/300x250', ['trackingCode' => $this->trackingCode, 'subId' => $this->subId]); ?>
                </div>
            </div>
        </div>
    </div>
</main>
