<main class="article">
    <div class="row">
        <div class="large-12 show-for-large-up column text-right social-widgets">
            <?php echo $this->partial('money-saving-news/partial/social-includes'); ?>
        </div>
    </div>
    <div class="row">
        <div class="small-12 large-9 column">
            <section class="article-content">
                <h1>
                    You won&rsquo;t believe what tigers can do!
                </h1>
                <?php echo $this->partial('money-saving-news/partial/article-author', ['articleDate' => $this->articleDate, 'articleLinkText' => $this->articleLinkText]); ?>
                <p>
                    Tigers are incredibly beautiful wild animals. Can you believe that tigers are skilled swimmers?! Unlike most other big cats, tigers love bathing and regularly play in the water! You won&rsquo;t believe these facts about the animal voted the world&rsquo;s favourite! 
                </p>
                <p>
                    1. Tigers have walked the planet for a LONG time. Fossil remains of the big cats have been found in China that is believed to be 2 million years old!
                </p>
                <p>
                    2. The legs of a tiger are incredibly strong. They&rsquo;ve been observed still standing even when they&rsquo;re dead!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/you-wont-believe-what-tigers-can-do/1.jpg" />
                    Image source: <a href="https://commons.wikimedia.org/wiki/File:Siberischer_tiger_de_edit02.jpg" rel="external">https://commons.wikimedia.org/wiki/File:Siberischer_tiger_de_edit02.jpg</a>
                </p>
                <p>
                    3. Tiger&rsquo;s brains weigh over 300g!
                </p>
                <p>
                    4. No two tigers have the same stripes; their markings are all totally unique and different, much like human fingerprints
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/you-wont-believe-what-tigers-can-do/3.jpg" />
                    Image source: <a href="https://commons.wikimedia.org/wiki/File:White_Tiger.png" rel="external">https://commons.wikimedia.org/wiki/File:White_Tiger.png</a>
                </p>
                <p>
                    5. A group of tigers is called a streak or an ambush.
                </p>
                <p>
                    6. The rare white tiger carries a gene which is only found in around 1 in every 10,000 tigers!
                </p>
                <p class="image-source image-full-width">
                    <img src="/images/article/you-wont-believe-what-tigers-can-do/2.jpg" />
                    Image source: <a href="http://thelife-animal.blogspot.co.uk/2012/06/bali-tiger.html" rel="external">http://thelife-animal.blogspot.co.uk/2012/06/bali-tiger.html</a>
                </p>
                <p>
                    7. Tigers have been known to imitate the call of other animals – making it easier to catch their prey!
                </p>
                <p>
                    8. The Bali Tiger was culled to the point of extinction in 1937 as they were viewed as a destructive force.
                </p>
                <p>
                    9. The saliva of a tiger is an antiseptic – they&rsquo;ll often lick their wounds to disinfect them.
                </p>
            </section>
            <?php echo $this->partial('money-saving-news/partial/more-to-explore'); ?>
        </div>
        <div class="small-12 large-3 column">
            <div class="trending">
                <?php echo $this->partial('money-saving-news/partial/trending'); ?>
            </div>
            <div class="row">
                <div class="stocks-shares column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/stocks'); ?>
                </div>
                <div class="column small-12 medium-6 large-12">
                    <?php echo $this->partial('money-saving-news/partial/banner/300x250', ['trackingCode' => $this->trackingCode, 'subId' => $this->subId]); ?>
                </div>
            </div>
        </div>
    </div>
</main>
