<main class="article">
    <div class="row">
        <div class="large-12 show-for-large-up column text-right social-widgets">
            <?php echo $this->partial('money-saving-news/partial/social-includes'); ?>
        </div>
    </div>
    <div class="row">
        <div class="small-12 large-9 column">
            <section class="article-content article-index">
                <h1>
                    Contact
                </h1>
                <p>
                    <strong>This website is owned and operated by</strong>
                </p>
                <p>
                    Live Life Protected Ltd.<br />
                    9 Funtley Court<br />
                    Funtley Hill<br />
                    Fareham<br />
                    Hampshire<br />
                    PO16 7UY
                </p>
                <ul>
                    <li>
                        <strong>Tel:</strong> 0800 524 4153<br />
                        From mobiles, it might be cheaper to call us on 01329 888 911
                    </li>
                    <li>
                        <strong>Fax:</strong> 0800 007 3410
                    </li>
                    <li>
                        <strong>Email:</strong> customerservice@protected.co.uk
                    </li>
                </ul>
                <p>
                    <strong>Complaints procedure</strong>
                </p>
                <p>
                    If you wish to register a complaint, please contact us:
                </p>
                <ul>
                    <li>
                        <strong>By email:</strong> Please send your complaints to customerservice@protected.co.uk
                    </li>
                    <li>
                        <strong>By phone:</strong> Call us on 01329 820 865
                    </li>
                    <li>
                        <strong>In writing:</strong> Send a letter to Complaints Department at Live Life Protected Ltd., 9 Funtley court, Funtley Hill, Fareham, Hampshire, PO16 7UY
                    </li>
                </ul>
                <p>
                    We will then investigate your complaint and get back to you.
                </p>
                <p>
                    If you cannot settle your complaint with us, you may be entitled to refer it to the Financial Ombudsman Service.
                </p>
            </section>
        </div>
        <div class="small-12 large-3 column">
            <div class="trending">
                <?php echo $this->partial('money-saving-news/partial/trending'); ?>
            </div>
            <div class="stocks-shares">
                <?php echo $this->partial('money-saving-news/partial/stocks'); ?>
            </div>
            <?php echo $this->partial('money-saving-news/partial/banner/300x250', ['trackingCode' => $this->trackingCode, 'subId' => $this->subId]); ?>
        </div>
    </div>
</main>
