<main class="article">
    <div class="row">
        <div class="large-12 show-for-large-up column text-right social-widgets">
            <?php echo $this->partial('money-saving-news/partial/social-includes'); ?>
        </div>
    </div>
    <div class="row">
        <div class="small-12 large-9 column">
            <section class="article-content article-index">
                <h1>
                    Privacy Policy
                </h1>
                <p>
                    This Privacy Policy applies to www.moneysavingnews.com and any information we collected on the Money Saving News Web site.
                </p>
                <ul>
                    <li>
                        <a href="#website">Who owns the website</a>
                    </li>
                    <li>
                        <a href="#tel">Telephone</a>
                    </li>
                    <li>
                        <a href="#cookies">Cookies</a>
                    </li>
                    <li>
                        <a href="#managing_cookies">Manage Your Cookies</a>
                    </li>
                    <li>
                        <a href="#info">Information we collect on the web site</a>
                    </li>
                    <li>
                        <a href="#data">What we use your data for</a>
                    </li>
                    <li>
                        <a href="#business">We run a business</a>
                    </li>
                    <li>
                        <a href="#data">Security of data</a>
                    </li>
                    <li>
                        <a href="#sensitive">Sensitive information</a>
                    </li>
                    <li>
                        <a href="#trans">Transferring to other websites</a>
                    </li>
                    <li>
                        <a href="#emails">Marketing E-mails</a>
                    </li>
                    <li>
                        <a href="#agree">Deemed agreement of this privacy policy</a>
                    </li>
                    <li>
                        <a href="#change">Our right to change this privacy policy</a>
                    </li>
                </ul>
                <a id="website"></a>
                <h4>
                    Who owns the web site
                </h4>
                <p>
                    Moneysavingnews.com is owned by Live Life Protected Limited who are an information society service who deal in financial services.
                </p>
                <p>
                    We are authorised and regulated by the Financial Conduct Authority for non-investment insurance mediation, regulated mortgage introduction and credit broking. You can check this out on the financial services register at <a href="http://www.fsa.gov.uk/register/firmSearchForm.do" rel="external">http://www.fsa.gov.uk/register/firmSearchForm.do</a> and our reference number is 441774.
                </p>
                <p>
                    For credit broking you can check us out on the interim permission consumer credit register at <a href="http://fca-consumer-credit-interim.force.com/CS_RegisterSearchPageNew" rel="external">http://fca-consumer-credit-interim.force.com/CS_RegisterSearchPageNew</a> under this reference number 549975.  We are a limited company and out company incorporated in England and Wales and our company reference number is 4906681. Our registered office and place of business is 9 Funtley Court, Funtley Hill, Fareham. Hampshire. PO16 7UY United Kingdom. We are listed with the Information Commissioners Office under reference Z8652661 you can check that out on this register <a href="https://ico.org.uk/esdwebpages/search" rel="external">https://ico.org.uk/esdwebpages/search</a>.
                </p>
                <a id="tel"></a>
                <h4>
                    Telephone
                </h4>
                <p>
                    From time to time we monitor and record telephone calls for training purposes, our mutual protection and to improve the services we provide.
                </p>
                <a id="cookies"></a>
                <h4>
                    Cookies
                </h4>
                <p>
                    Cookies are a means by which information relating to your Internet activity (such as whether you have visited our website before) is recorded on your computer's hard drive. This information may be used to improve our website and the products and services available to you.
                </p>
                <p>
                    If you do not wish for us to use cookies when you use this site please adjust your Internet browser settings to not accept cookies. We've written a guide to managing your cookieshere.
                </p>
                <p>
                    If you set your web browser not to allow cookies, parts of our web site systems that require cookies to be enabled may not operate to their full potential.
                </p>
                <p>
                    The following tables explain the cookies we use and why we use them.
                </p>
                <p>
                    <strong>Google Analytics</strong>
                </p>
                <p>
                    Google Analytics provides us with anonymous information on the way people use our website, which enables us to improve our customer experience.
                </p>
                <table>
                    <tr>
                        <td>_utma</td>
                        <td>This cookie identifies unique visitors by assigning them a unique ID upon their first visit to your site. It will last 2 years so long as the user does not delete it. At the 2-year mark, it will expire.</td>
                    </tr>
                    <tr>
                        <td>_utmb</td>
                        <td>This cookie generates data about a visitor's session. It establishes or updates a session every time a page of a site is visited. If it is not updated, it expires by default after 30 minutes.</td>
                    </tr>
                    <tr>
                        <td>_utmc</td>
                        <td>This cookie works hand in hand with _utmb. It expires only when a user quits a browser.</td>
                    </tr>
                    <tr>
                        <td>_utmz</td>
                        <td>This cookie determines what brought a user to your site. This cookie tracks things like PPC ads, organic search, and referring links.  It also tracks page navigation so that you can see how visitors move through your site. This cookie expires after 6 months unless it is updated. Updates occur when a page view initiates.</td>
                    </tr>
                </table>
                <p>
                    <strong>Other</strong>
                </p>
                <table>
                    <tr>
                        <td>PHPSESSID</td>
                        <td>This cookie enables our server to record session activity and allows you to access parts of out website.</td>
                    </tr>
                    <tr>
                        <td>visitor_hash</td>
                        <td>This cookie is used to track visitors across site visits, for example to track when a visitor returns to the moneysavingnews.com at a later time. It is deleted after 10 years</td>
                    </tr>
                </table>
                <p>
                    To opt out of being tracked by Google Analytics across all websites visit <a href="http://tools.google.com/dlpage/gaoptout" rel="external">http://tools.google.com/dlpage/gaoptout</a>.
                </p>
                <a id="managing_cookies"></a>
                <h4>
                    Manage your cookies
                </h4>
                <p>
                    Cookies are managed slightly differently in the all the web browsers available. If you&rsquo;re not sure of the type and version of web browser you use, follow these steps:
                </p>
                <ul>
                    <li><strong>For PCs:</strong> click on &lsquo;Help&rsquo; at the top of your browser window and select the &lsquo;About&rsquo; option</li>
                    <li><strong>For Macs:</strong> with the browser window open, click on the Apple menu and select the &lsquo;About&rsquo; option</li>
                </ul>
                <p>
                    <strong>How to check cookies are enabled for PCs</strong>
                </p>
                <p>
                    <strong>Google Chrome</strong>
                </p>
                <ol>
                    <li>Click on &lsquo;Tools&rsquo; at the top of your browser window and select Options</li>
                    <li>Click the &lsquo;Under the Hood&rsquo; tab, locate the &lsquo;Privacy&rsquo; section, and select the &lsquo;Content settings&rsquo; button</li>
                    <li>Now select &lsquo;Allow local data to be set&rsquo;</li>
                </ol>
                <p>
                    <strong>Internet Explorer 6.0, 7.0, 8.0</strong>
                </p>
                <ol>
                    <li>Click on &lsquo;Tools&rsquo; at the top of your browser window and select &lsquo;Internet options&rsquo;, then click on the &lsquo;Privacy&rsquo; tab</li>
                    <li>Ensure that your Privacy level is set to Medium or below, which will enable cookies in your browser</li>
                    <li>Settings above Medium will disable cookies</li>
                </ol>
                <p>
                    <strong>Mozilla Firefox</strong>
                </p>
                <ol>
                    <li>Click on &lsquo;Tools&rsquo; at the top of your browser window and select Options</li>
                    <li>Then select the Privacy icon</li>
                    <li>Click on Cookies, then select 'allow sites to set cookies'</li>
                </ol>
                <p>
                    <strong>Safari</strong>
                </p>
                <ol>
                    <li>Click on the Cog icon at the top of your browser window and select the &lsquo;Preferences&rsquo; option</li>
                    <li>Click on &lsquo;Security&rsquo;, check the option that says &lsquo;Block third-party and advertising cookies&rsquo;</li>
                    <li>Click &lsquo;Save&rsquo;</li>
                </ol>
                <p>
                    <strong>How to check cookies are enabled for Macs</strong>
                </p>
                <p>
                    <strong>Safari on OSX</strong>
                </p>
                <ol>
                    <li>Click on &lsquo;Safari&rsquo; at the top of your browser window and select the &lsquo;Preferences&rsquo; option</li>
                    <li>Click on &lsquo;Security&rsquo; then &lsquo;Accept cookies&rsquo;</li>
                    <li>Select the &lsquo;Only from site you navigate to&rsquo;</li>
                </ol>
                <p>
                    <strong>Opera</strong>
                </p>
                <ol>
                    <li>Click on &lsquo;Menu&rsquo; at the top of your browser window and select &lsquo;Settings&rsquo;</li>
                    <li>Then select &lsquo;Preferences&rsquo;, select the &lsquo;Advanced&rsquo; tab</li>
                    <li>Then select &lsquo;Accept cookies&rsquo; option</li>
                </ol>
                <a id="info"></a>
                <h4>
                    Information we collect on the web site
                </h4>
                <p>
                    We do use cookies and those are explained above. Those cookies do collect information as described above.
                </p>
                <p>
                    If you use any of the links on our web site then we will measure you use of those links. This helps us to identify which links are of most interest to web site visitors.
                </p>
                <p>
                    We may display enquiry forms on our web site so that you can register to receive an enquiry. When we do the forms will explain the subject matter of that enquiry.
                </p>
                <p>
                    We may run a news letter or an advice service. If we do then we would ask you to sign up for that service. When you sign us up the service will be explained.
                </p>
                <p>
                    We may run competitions an if we do then the completion entry format will be explained when you register to enter that competition.
                </p>
                <p>
                    When entering or registering for specific items on our web site we may also offer you the opportunity to also register for other services at the same time. This will be explained at the time and you will always be given an &lsquo;opt out&rsquo; option.
                </p>
                <a id="data"></a>
                <h4>
                    What we use your data for
                </h4>
                <p>
                    We use Google analytical, cookies and measurement of the use of links in order to improve our web site for your future use and the use of others.
                </p>
                <p>
                    Data collected via enquiry forms, competition entry, sign up for newsletters will always be used firstly to provide the service you have signed up for. We may also use that information to keep you up to date with other services we offer or special offers we think may be of interest to you.
                </p>
                <p>
                    The communication medium we use will be dependent on the contact details you have given to us. We reserve the right to select which communication medium we will use, unless we specifically advise that some services can only be offered through a single communication medium. 
                </p>
                <a id="business"></a>
                <h4>
                    We run a business
                </h4>
                <p>
                    We run a business and as with most businesses we need to use suppliers, professionals, service systems and also provide certain reports. On occasion your information may form part of our business processes where that information does get handled by others. For instance we use an external company to manage some of our servers where data is held.
                </p>
                <p>
                    Because business is getting more international, some data may be held or worked on overseas outside the EEA.
                </p>
                <a id="business"></a>
                <h4>
                    Security of data
                </h4>
                <p>
                    We treat all data as if it was our own personal data then it comes to security. We have locks on the external doors and we utilise alarm systems. Computers and servers are backed up to avoid data loss. Access to our internal systems are accessed by pass word protected log in and we restrict access to certain folders by use of access controls. No system can ever be 100% secure but we do take reasonable precautions. We reserve the right to modify the precautions we take depending on the data being stored or handled. 
                </p>
                <p>
                    We check out supplies and generally we would only allow a supplier to store or process your data if we would also allow them to store and process our own personal data.
                </p>
                <a id="sensitive"></a>
                <h4>
                    Sensitive information
                </h4>
                <p>
                    We will never collect sensitive information about you without your explicit consent. An example of sensitive information would be your religion or a medical condition.
                </p>
                <a id="trans"></a>
                <h4>
                    Transferring to other web sites
                </h4>
                <p>
                    If you transfer to another web site from this web site, then any information you provide on the other web site, or any information that web sites collects about you, will be subject to the Privacy Policy of that other web site. This includes other web sites runs by us.
                </p>
                <p>
                    We run several web sites and each web site has a specific purpose. Depending on that purpose there may be differing privacy considerations and different people we have to share data with. Therefore each of our Web Sites has it&rsquo;s own Privacy Policy.
                </p>
                <a id="emails"></a>
                <h4>
                    Marketing E-mails
                </h4>
                <p>
                    If we send you any e-newsletters, marketing e-mails or other promotional e-mails then those e-mails will contain an unsubscribe option giving you the right to unsubscribe to future e-mails of that type. If at a later date you want to re-subscribe then you can easily do so on this web site, if we are still offering that service.
                </p>
                <a id="agree"></a>
                <h4>
                    Deemed agreement of this privacy policy
                </h4>
                <p>
                    This web site is subject to this Privacy Policy. By using this web site it will be deemed that you have accepted this privacy Policy. If at any time you are unhappy with this Privacy Policy then you should decide whether or not you want to continue to use this web site. Continuing to use this web site will mean that you are agreeing to this Privacy Policy.
                </p>
                <p>
                    We may on occasion bring this Privacy Policy to your attention and ask you to reconfirm your agreement to this Privacy Policy.
                </p>
                <a id="change"></a>
                <h4>
                    Our right to change this privacy policy
                </h4>
                <p>
                    We have the right to vary or change this Privacy Policy at any time completely at our discretion. When we do change it the new Privacy Policy will be displayed here on this web site. The version applicable you at any one time will be the version that is displayed at the time of your web site visit.
                </p>
            </section>
        </div>
        <div class="small-12 large-3 column">
            <div class="trending">
                <?php echo $this->partial('money-saving-news/partial/trending'); ?>
            </div>
            <div class="stocks-shares">
                <?php echo $this->partial('money-saving-news/partial/stocks'); ?>
            </div>
            <?php echo $this->partial('money-saving-news/partial/banner/300x250', ['trackingCode' => $this->trackingCode, 'subId' => $this->subId]); ?>
        </div>
    </div>
</main>
